### ISSUE TITLE
[Suggestion] Store audio device on a variable before switching, then switch back to said device when disconnected

### ISSUE THREAD

**Issue by thedaryen** [ArthurVaiselbuh/HeadsetUtils#3]
Instead of pointing an specific audio device on the config, it'd be better if the program could store your current audio device on a variable before switching to the headset. Then, when the headset is disconnected, HeadsetUtils would swap back to that audio device.

My use case: my PC is connected both to the TV speakers on the living room and to it's monitor and an Edifier 2.1 speaker setup on my office. I tend to switch the main display and audio back and forth depending on where I am (I use an Autohotkey script for easy swapping), so sometimes I'll use my headset on one setup and sometimes on the other.

Other use cases: any setup that features more than one audio device + the wireless headset will benefit from such change.

**Comment by ArthurVaiselbuh** [comment]
This has a few edge cases such as the headset was on before `HeadsetUtils` started running, the previous device is no longer connected when the headset is turned off, etc.

I think a better solution for this scenario would be a prioritized list of devices instead of a single default device to switch to, and try changing the device in order of that list.

If you're interested in implementing something like this and opening a PR I'm willing to look at it but generally speaking I'm not interested at implementing this myself
